staging_build:
  stage: build
  tags:
    - builder
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
    - echo "Building 3Bot Connect for staging"

staging_deploy:
  stage: deploy
  tags:
    - 3botconnect_staging_deploy
  script:
    - echo "Deploying 3Bot Connect for staging"

production_build:
  stage: build
  tags:
    - builder
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
    - echo "Building 3Bot Connect for production"

production_deploy:
  when: manual
  stage: deploy
  tags:
    - 3botconnect_production_deploy
  script:
    - echo "Deploying 3Bot Connect for production"
            
    // docker login --username singlecore
    // 29ae6bdf-cc87-4631-b7e1-c3dd0867995c
    29ae6bdf-cc87-4631-b7e1-c3dd0867995c