# Default values for 3botlogin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: testing

images:
  login:
    name: threebotlogin-testing
    tag: testing-v1.5.6-test10
  wizard:
    name: wizard-prod
    tag: prodv1




ingress:
  # Used to create an Ingress record.
  hosts:
    - name: login-helm-testing.jimbertesting.be
      # default paths for "/" and "/*" will be added
      path: /
      service: threebotlogin-testing
      port: 80
    - name: login-helm-testing.jimbertesting.be
      path: /socket.io/
      service: threebotlogin-testing
      port: 3030
    - name: wizard-helm-testing.jimbertesting.be
      path: /
      service: threebotlogin-testing
      port: 82
