# Default values for 3botlogin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: staging

images:
  login:
    name: threebotlogin-staging
    tag: staging-2
  wizard:
    name: wizard-prod
    tag: latest


ingress:
  # Used to create an Ingress record.
  hosts:
    - name: login-helm-staging.jimbertesting.be
      # default paths for "/" and "/*" will be added
      path: /
      service: threebotlogin-staging
      port: 80
    - name: login-helm-staging.jimbertesting.be
      path: /socket.io/
      service: threebotlogin-staging
      port: 5000
    - name: wizard-helm-staging.jimbertesting.be
      path: /
      service: wizard-prod
      port: 82
