# Default values for 3botlogin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: staging

images:
  login:
    repo: threefolddev/3botlogin
    name: threebotlogin-staging
    
    tag: staging-2
  wizard:
    repo: threefolddev/wizard
    name: wizard-staging
    tag: latest


ingress:
  # Used to create an Ingress record.
  hosts:
    - name: login.staging.threefold.me
      # default paths for "/" and "/*" will be added
      path: /
      service: threebotlogin-staging
      port: 80
    - name: login.staging.threefold.me
      path: /socket.io/
      service: threebotlogin-staging
      port: 5000
    - name: wizard.staging.threefold.me
      path: /
      service: wizard-staging
      port: 82
