apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "releaseName" . }}
  name: {{ template "releaseName" . }}
spec:
  ports:
    - name: {{ .Values.services.app.name }}
      port: {{ .Values.services.app.port }}
      protocol: TCP
      targetPort: {{ .Values.services.app.targetPort }}
    - name: {{ .Values.services.uwsgi.name }}
      port: {{ .Values.services.uwsgi.port }}
      protocol: TCP
      targetPort: {{ .Values.services.app.targetPort }}
  selector:
    app: {{ template "releaseName" . }}
  type: ClusterIP
status:
  loadBalancer: {}
