apiVersion: apps/v1
kind: Deployment
metadata:
        name: {{ template "releaseName" .}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "releaseName" . }}
  template:
    metadata:
      labels:
        app: {{ template "releaseName" . }}
    spec:
      containers:
        - name: {{ .Values.images.login.name }}
          image: {{ .Values.images.login.repo }}:{{ .Values.images.login.tag }}
          ports:
                  - containerPort: {{ .Values.images.login.containerPort}}
          volumeMounts:
          - name: threebotlogin-data
            mountPath: /usr/share/nginx/backend/persistantVolume
          command: ["/bin/sh","-c"]
          # if is prod db comes from /persistentVolume/db/ otherwise from /persistentVolume..
          {{ if eq .Values.environment "prod" }}
          args: [" ln -sfn persistantVolume/config.ini . &&  ln -sfn persistantVolume/db/pythonsqlite.db . &&  /bin/sh /./services.sh"] 
          {{ else }}
          args: [" ln -sfn persistantVolume/config.ini . &&  ln -sfn persistantVolume/pythonsqlite.db . && /bin/sh /./services.sh"] 
          {{ end }}
      volumes:
      - name: threebotlogin-data 
        persistentVolumeClaim:
          claimName: {{ .Values.claims.data.name }}
          
