apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.claims.data.name }}
  namespace: jimber
spec:
  accessModes:
  - {{ .Values.claims.data.accessModes }}
  resources:
    requests:
      storage: {{ .Values.claims.data.storage }}
  storageClassName: rook-cephfs