apiVersion: apps/v1
kind: Deployment
metadata:
        name: {{ .Values.images.wizard.name}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.images.wizard.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.images.wizard.name}}
    spec:
      containers:
        - name: {{ .Values.images.wizard.name }}
          image: {{ .Values.images.wizard.repo }}:{{ .Values.images.wizard.tag}}
          ports:
                  - containerPort: {{ .Values.images.wizard.containerPort}}

          
