apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.images.wizard.name }}
  name: {{ .Values.images.wizard.name }}
spec:
  ports:
    - port: {{ .Values.services.wizard.port }}
      protocol: TCP
      targetPort: {{ .Values.services.wizard.targetPort }}
  selector:
    app: {{ .Values.images.wizard.name }}
  type: ClusterIP
status:
  loadBalancer: {}
