name: threebotlogin
description: A decentralized login application

publish_to: "none"

version: 3.4.3+140

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  gson: ^0.1.4
  flutter:
    sdk: flutter
  qr_code_scanner:
    git:
      url: https://github.com/jimbertools/qr_code_scanner
  flutter_sodium:
    git:
      url: https://github.com/jimbertools/flutter_sodium
  uni_links:
    git:
      url: https://github.com/jimbertools/uni_links
  flutter_inappwebview: ^5.2.0
  keyboard_visibility:
    git:
      url: https://github.com/jimbertools/flutter_keyboard_visibility

  redirection:
    git:
      url: https://github.com/jimbertools/redirection

  shuftipro_flutter_sdk:
    git:
      url: git@github.com:jimbertools/shufti-jimber.git
      ref: main_integration-dependencies

  flutter_pkid:
    git:
      url: git@github.com:threefoldtech/flutter-pkid-client.git
      ref: main_integration-dependencies

  country_picker:
    git:
      url: git@github.com:jimbertools/flutter-country-picker.git
      ref: main

  yggdrasil_plugin:
    git:
      url: https://github.com/threefoldtech/yggdrasil_flutter

  flutter_svg: ^0.19.3
  crypto: ^2.1.5
  bip39: ^1.0.3
  uuid: ^2.2.0
  socket_io_client: ^1.0.1
  local_auth: ^1.1.6
  url_launcher: ^6.0.2
  intl: ^0.17.0
  password_hash: ^2.0.0
  shared_preferences: ^0.5.12+4
  http: ^0.12.2
  package_info: ^0.4.1
  cupertino_icons: ^1.0.2
  google_fonts: ^1.1.1
  international_phone_input: ^1.0.4
  intl_phone_field: ^1.4.2
  flagsmith: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/circle_images/
    - assets/icons/
    - assets/
